### ISSUE TITLE
Trying to implement for the first time.

### ISSUE THREAD

**Issue by fftaha** [jlukenichols/KUDellWarrantyChecker#1]
I have run the KUDellWarrantyChecker.ps1 with no errors. The output DellWarrantyData.CSV does not include any data except for the Computer,Name,Purchase,Date,Warranty,End Date in row 1. I have a PDQ report setup, but it is not an auto-report. Am I missing something? Do I need to add custom fields to PDQ Inventory? Any assistance would be greatly appreciated. I also posted on the PDQ forum.

Thank you,
Fareed

**Comment by jlukenichols** [comment]
Fareed,

Yes, you will need to create two custom variables. I have included a screenshot.
![PDQInvCustomVariables](https://user-images.githubusercontent.com/41305706/125512727-4c5d025a-2918-4912-a212-d3d6fc41dc4a.png)

Let me know if it works after you create those variables.

**Comment by fftaha** [comment]
Thank you. I have made those changes, but I still do not see any results within PDQ Inventory.  I have not worked with API's before. I presume that the Client ID is the part of the key before the parenthesis and the secret key is within the parenthesis. Is this correct?
 I am not getting any errors.
![2021-07-14_13-26-26](https://user-images.githubusercontent.com/87376105/125665872-11a0b0b8-b19e-4035-a48a-aac0c36bcb88.png)

**Comment by jlukenichols** [comment]
It looks like you are trying to use an excel spreadsheet as the input file. That won't work, it has to be a CSV file. You can open it in excel and save as a CSV or you can modify your PDQ Inventory report to output as a CSV instead.

Also yes, you are correct. The Client ID is the string before the parentheses and the secret key is the string within the parentheses.

**Comment by fftaha** [comment]
(-_-) ...

Well I am dumb...

That worked. I cannot thank you enough. This is a huge help to my reporting metrics.
