### ISSUE TITLE
Script Issue

### ISSUE THREAD

**Issue by ice2921** [jlukenichols/KUDellWarrantyChecker#5]
Hello I am having the same issues as this post:
https://github.com/jlukenichols/KUDellWarrantyChecker/issues/1
the only difference I am using a csv file.

Here is the start of the script
![image](https://user-images.githubusercontent.com/2303699/180245743-8fa7d452-0747-48a4-8315-7e2bfa612356.png)

And here is the end of the script
![image](https://user-images.githubusercontent.com/2303699/180245846-e805f491-ed00-4db1-8f37-1c5e2d488265.png)

**Comment by jlukenichols** [comment]
Joe,

What is the header line for your CSV input file?

**Comment by ice2921** [comment]
It was header issue. This can be closed thanks!
