### ISSUE TITLE
Write-Log Error

### ISSUE THREAD

**Issue by jaysalazar** [jlukenichols/KUDellWarrantyChecker#7]
I have used this script in the past succesfully (couple years ago) however when I try to run it now I get the following error message. 

![image](https://github.com/user-attachments/assets/ff01e73e-7b31-4ade-a919-754ae3d18190)

**Edit**
Nevermind, forgot to pull the function folder.

**Comment by jlukenichols** [comment]
Glad you got it figured out, I'll mark this as closed.
